"""Editing the generated narration: save edits, regenerate a slide, keep index / pointer map / audio consistent."""
from __future__ import annotations

import asyncio
import logging

from ..services import Services
from .cursor import CursorMatcher
from .narration import brief_for, generate_slide_narration
from .sentences import split_sentences

log = logging.getLogger("ingest.script")

MAX_SENTENCES = 60
MAX_SENTENCE_CHARS = 600


class ScriptError(ValueError):
    pass


def clean_sentences(sentences: list[str] | None, text: str | None) -> list[str]:
    if sentences is None:
        sentences = split_sentences(text or "")
    out = [" ".join(s.split()) for s in sentences if s and s.strip()]
    if not out:
        raise ScriptError("the script for a slide cannot be empty")
    if len(out) > MAX_SENTENCES:
        raise ScriptError(f"too many sentences (max {MAX_SENTENCES})")
    for s in out:
        if len(s) > MAX_SENTENCE_CHARS:
            raise ScriptError(f"a sentence is longer than {MAX_SENTENCE_CHARS} characters; split it")
    return out


async def save_slide_script(svc: Services, deck_id: str, n: int, sentences: list[str], model: str = "edited") -> dict:
    """Persist new sentences for slide n and refresh everything derived from them."""
    store = svc.store
    narr = store.narration(deck_id)
    entry = next((x for x in narr if x["n"] == n), None)
    if entry is None:
        raise KeyError(n)
    old_count = len(entry["sentences"])
    entry["sentences"] = sentences
    entry["model"] = model
    store.write_narration(deck_id, narr)

    # audio files beyond the new length are orphans; changed sentences are regenerated by the cache (text hash)
    for i in range(len(sentences), old_count):
        for suffix in (".mp3", ".meta.json"):
            store.audio_path(deck_id, n, i).with_suffix(suffix).unlink(missing_ok=True)

    slides = store.slides(deck_id)

    def derived():
        svc.kb.index_slides(deck_id, slides, narr)
        layout = store.layout(deck_id)
        if layout:
            cmap = store.cursor_map(deck_id) or {}
            m = CursorMatcher(layout, svc.kb.embedder)
            cmap[str(n)] = [m.match(n, t) for t in sentences]
            store.write_cursor_map(deck_id, cmap)

    try:
        await asyncio.to_thread(derived)
    except Exception as e:  # the script is saved either way
        log.warning("re-index after script edit failed: %s", e)
    return entry


async def regenerate_slide_script(svc: Services, deck_id: str, n: int, instruction: str = "", tone: str | None = None,
                                  length: str | None = None) -> list[str]:
    store = svc.store
    slides = store.slides(deck_id)
    idx = next((i for i, s in enumerate(slides) if s["n"] == n), None)
    if idx is None:
        raise KeyError(n)
    meta = store.meta(deck_id)
    current = next((x for x in store.narration(deck_id) if x["n"] == n), {"sentences": []})
    text, model = await generate_slide_narration(
        svc.llm, svc.settings, brief_for(slides, idx), tone or meta.get("tone", "conversational"),
        length or meta.get("length", "standard"), instruction=instruction.strip()[:300],
        previous=" ".join(current["sentences"]) if instruction.strip() else "")
    sentences = clean_sentences(None, text)
    await save_slide_script(svc, deck_id, n, sentences, model=model)
    return sentences


async def rewrite_all(svc: Services, deck_id: str, tone: str, length: str, instruction: str = "") -> None:
    """Rewrite every slide's script with a new tone/length (sequential: Groq free tier), then re-voice what changed."""
    from ..tts.pregen import pregenerate_deck_audio

    store = svc.store
    slides = store.slides(deck_id)
    store.update_meta(deck_id, tone=tone, length=length, rewrite={"done": 0, "total": len(slides), "running": True, "error": None})
    try:
        for k, sl in enumerate(slides, start=1):
            if not store.alive(deck_id):
                return
            await regenerate_slide_script(svc, deck_id, sl["n"], instruction, tone, length)
            store.update_meta(deck_id, rewrite={"done": k, "total": len(slides), "running": True, "error": None})
        store.update_meta(deck_id, rewrite={"done": len(slides), "total": len(slides), "running": False, "error": None})
    except Exception as e:
        log.warning("rewrite-all failed: %s", e)
        m = store.meta(deck_id).get("rewrite", {})
        store.update_meta(deck_id, rewrite={**m, "running": False, "error": str(e)[:200]})
        return
    try:
        await pregenerate_deck_audio(svc, deck_id)
    except Exception as e:
        log.warning("audio after rewrite failed: %s", e)
